categories:
  - name: "Unit Tests"
    subcategories:
      - name: "Login"
        tests:
          - name: "Login button visible"
            marker: "login"
            type: "normal"
          - name: "Login button clickable"
            marker: "logout"
            type: "normal"
          - name: "Login button enabled"
            marker: "testing"
            type: "normal"
      - name: "Navigation"
        tests:
          - name: "Navigation bar visible"
            marker: "menu"
            type: "normal"
          - name: "Navigation bar clickable"
            marker: "test"
            type: "normal"
  - name: "Images"
    subcategories:
      - name: "Mode"
        tests:
          - name: "Image rendering"
            marker: "users"
            type: "special"
            arguments:
              - name: "action"
                arg_type: "select"
                options: ["Add image", "Delete image", "Copy image"]
              - name: "image"
                arg_type: "text_input"
                placeholder: "Enter image name"
