categories:
  - name: "Unit Tests"
    subcategories:
      - name: "Login"
        tests:
          - name: "Login button visible"
            markers: ["login"]
            type: "normal"
          - name: "Login button clickable"
            markers: ["login", "logout"]
            type: "normal"
          - name: "Login button enabled"
            markers: ["login", "testing"]
            type: "normal"
      - name: "Navigation"
        tests:
          - name: "Navigation bar visible"
            markers: ["navigation"]
            type: "normal"
          - name: "Navigation bar clickable"
            markers: ["navigation", "logout"]
            type: "normal"
  - name: "Images"
    subcategories:
      - name: "Mode"
        tests:
          - name: "Image rendering"
            markers: ["users"]
            type: "special"
            arguments:
              - name: "action"
                arg_type: "select"
                options: ["Add image", "Delete image", "Copy image"]
              - name: "image"
                arg_type: "text_input"
                placeholder: "Enter image name"
